"""empty message

Revision ID: 34c59eee3cff
Revises: e5189f29c1b7
Create Date: 2021-10-01 06:51:20.527431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c59eee3cff'
down_revision = 'e5189f29c1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
