"""empty message

Revision ID: 4fe6bbf934e4
Revises: c4171b26a4a6
Create Date: 2021-09-15 12:41:44.284235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe6bbf934e4'
down_revision = 'c4171b26a4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
