"""empty message

Revision ID: e5189f29c1b7
Revises: 9f89ef6604e8
Create Date: 2021-09-30 13:36:40.661730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5189f29c1b7'
down_revision = '9f89ef6604e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('glass_manufacture_price_glass_id_fkey', 'glass_manufacture_price', type_='foreignkey')
    op.drop_constraint('glass_manufacture_price_manufacture_id_fkey', 'glass_manufacture_price', type_='foreignkey')
    op.create_foreign_key(None, 'glass_manufacture_price', 'glass_type', ['glass_id'], ['id'])
    op.create_foreign_key(None, 'glass_manufacture_price', 'glass_manufacture', ['manufacture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'glass_manufacture_price', type_='foreignkey')
    op.drop_constraint(None, 'glass_manufacture_price', type_='foreignkey')
    op.create_foreign_key('glass_manufacture_price_manufacture_id_fkey', 'glass_manufacture_price', 'glass_manufacture', ['manufacture_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('glass_manufacture_price_glass_id_fkey', 'glass_manufacture_price', 'glass_type', ['glass_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
